apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-value
data:
  prometheus.yaml: |
    global:
        scrape_interval: 5s
        evaluation_interval: 5s

        scrape_configs:
        - job_name: 'movies-api'
            metrics_path: '/actuator/prometheus'
            static_configs:
            - targets: ['webapp:9090']
                labels: 
                application: "Product App"    
  