apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    name: kibana-service
    app: elk-stack

spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    name: kibana-pod
    app: elk-stack
