global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'movies-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webapp:8080']
        labels: 
          application: "Product App"