deploymentName : elasticsearch-deployment
deploymentLabel : elasticsearch

replicaCount: 1

image:
  repository: elasticsearch
  tag: 7.16.2

service:
  type: ClusterIP
  port: 9200
  targetPort: 9200

