version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: localhost
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - $PWD/cicd/gitlab/config:/etc/gitlab
      - $PWD/cicd/gitlab/logs:/var/log/gitlab
      - $PWD/cicd/gitlab/data:/var/opt/gitlab
    networks:
      - cicd
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    container_name: gitlab-runner
    restart: always
    depends_on:
      - web
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - $PWD/cicd/gitlab-runner:/etc/gitlab-runner
    networks:
      - cicd
  SonarQube:
    image: 'sonarqube:8.6.1-community'
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: 'jdbc:postgresql://db:5432/sonar'
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - $PWD/cicd/sonar/data:/opt/sonarqube/data
      - $PWD/cicd/sonar/extensions:/opt/sonarqube/extensions
      - $PWD/cicd/sonar/logs:/opt/sonarqube/logs
      - $PWD/cicd/sonar/plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.6.0.jar
      - $PWD/cicd/sonar/plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.6.0.jar
    ports:
      - '9000:9000'
    networks:
      - cicd
  db:
    image: 'postgres:12'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - $PWD/cicd/postgres/:/var/lib/postgresql
      - $PWD/cicd/postgres/data:/var/lib/postgresql/data
    networks:
      - cicd

  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    volumes:
      - $PWD/cicd/nexus/data:/sonatype-work
    ports:
     - '8081:8081'
     - '8085:8085'
    networks:
      - cicd


networks:
  cicd:
    name: cicd-network
