version: '3.7'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: localhost
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - cicd
  gitlab-runner:
    image: 'gitlab/gitlab-runner:alpine'
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./gitlab-runner:/etc/gitlab-runner
    networks:
      - cicd
  SonarQube:
    image: 'sonarqube:8.6.1-community'
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: 'jdbc:postgresql://db:5432/sonar'
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/extensions:/opt/sonarqube/extensions
      - ./sonar/logs:/opt/sonarqube/logs
      - ./sonar/plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin-1.6.0.jar
      - ./sonar/plugins/sonarqube-community-branch-plugin-1.6.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin-1.6.0.jar
    ports:
      - '9000:9000'
    networks:
      - cicd
  db:
    image: 'postgres:12'
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgres/:/var/lib/postgresql
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - cicd

  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    volumes:
      - ./nexus/data:/sonatype-work
    ports:
     - '8081:8081'
     - '8085:8085'
    networks:
      - cicd


networks:
  cicd:
    name: cicd-network
