apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-pod
  labels: 
    name: elasticsearch-pod
    app: elk-stack

spec:
  containers:
    - name: elasticsearch
      image: elasticsearch:7.16.2
