apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
    app: elk-stack

spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    name: elasticsearch-pod
    app: elk-stack   