apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  labels:
    name: filebeat-deployment
    app: elk-stack

spec:
  template:
    metadata:
      name: filebeat-pod
      labels:
        name: filebeat-pod
        app: elk-stack
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.16.2
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch:9200"
          volumeMounts:
            - mountPath: /data/filebeat/
              name: elk-data-storage
              subPath: filebeat.yml
            - mountPath: /data/logs/
              name:  elk-data-storage
              subPath: spring.log

      volumes:
        - name: elk-data-storage
          persistentVolumeClaim:
            claimName: elk-persistentvolumeclaim
              
  selector:
    matchLabels:
      name: filebeat-pod
      app: elk-stack
