apiVersion: v1
kind: Pod
metadata:
  name: filebeat-pod
  labels:
    name: filebeat-pod
    app: elk-stack

spec:
  containers:
    - name: filebeat-pod
      image: docker.elastic.co/beats/filebeat:7.16.2
