{{- define "common.ingress" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.service.name }}

spec:
  rules:
    - host: {{.Values.service.name}}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{.Values.service.name}}
              port:
                number: {{ .Values.service.exposePort}}

{{- end -}}                