{{- define "common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ .Values.service.name }}
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .externalPort }}
      targetPort: {{ .internalPort }}
      nodePort: {{.nodePort}}
  {{- end -}}
{{- end -}}
