apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-elk

spec:
  rules:
    - host: kibana
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kibana-service
              port:
                number: 5601


