apiVersion: 1

deleteDatasources:
  - name: Tempo

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    editable: true
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'