deploymentName : webapp-example
deploymentLabel : webapp

replicaCount: 1

image:
  repository: pranayraut11/simple-webapp
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 32762

config:
  enabled: true
profile:
  enabled: true

global:
  configMapName: dev-configmap
  activeProfile: dev