elasticsearch:
  enabled: true
  service:
    xpack: 
      enabled: true
    envVars:
      - name: ES_JAVA_OPTS
        value: -Xmx256m -Xms256m
      - name: discovery.type
        value: single-node
      - name: xpack.security.enabled
        value: false
      # - name: xpack.security.authc.api_key.enabled
      #   value: true
      # - name: xpack.monitoring.collection.enabled
      #   value: true  
      - name : ELASTIC_PASSWORD
        value: password

kibana:
  enabled: true  
  service:
    envVars:
      - name: ELASTICSEARCH_URL
        value: http://elasticsearch:9200
      - name: ELASTICSEARCH_USERNAME
        value: "elastic"
      - name: ELASTICSEARCH_PASSWORD
        value: "password"